server:
  type: simple
  applicationContextPath: /
  rootPath: '/api/*'
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: WARN
  appenders:
    - type: console

amazon:
  access: 'AWS ACCESS KEY HERE'
  secret: 'AWS SECRET HERE'
  bucket: 'AWS BUCKET NAME HERE'
